package com.kanban.model;

import jakarta.persistence.*;
import java.time.Instant;

/**
 * WHY: JPA entity representing one Kanban card persisted in PostgreSQL.
 * Holds title, optional description, column status, and sort position
 * so the board can render ordered columns and survive restarts.
 */
@Entity
@Table(name = "cards")
public class Card {

    /** WHY: Surrogate primary key generated by the DB for stable card identity. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** WHY: Short label shown on the card face — required for a usable board. */
    @Column(nullable = false, length = 200)
    private String title;

    /** WHY: Optional longer notes; nullable so quick cards stay lightweight. */
    @Column(length = 2000)
    private String description;

    /**
     * WHY: Which column the card lives in (TODO / IN_PROGRESS / DONE).
     * Stored as string for readable SQL and simple frontend mapping.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 32)
    private CardStatus status;

    /**
     * WHY: Sort order within a column so drag-drop / move can reorder cards
     * without relying on id or createdAt.
     */
    @Column(nullable = false)
    private Integer position;

    /** WHY: Audit timestamp so the UI can show when a card was created. */
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /** WHY: JPA requires a no-arg constructor for entity instantiation. */
    public Card() {
    }

    /**
     * WHY: Convenience constructor used by the seeder and create flow
     * so callers do not forget required fields.
     */
    public Card(String title, String description, CardStatus status, Integer position) {
        this.title = title;
        this.description = description;
        this.status = status;
        this.position = position;
    }

    /** WHY: Stamp createdAt once before first insert so every row has a time. */
    @PrePersist
    protected void onCreate() {
        if (createdAt == null) {
            createdAt = Instant.now();
        }
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public CardStatus getStatus() {
        return status;
    }

    public void setStatus(CardStatus status) {
        this.status = status;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }
}
